### PR TITLE
Ad/nginx validation

### PR DESCRIPTION
**Pull request by allie-drake**
* Refactor & modernization of the circle-ci config file (also moved it to `.circleci/config.yml` so that it can be debugged in the dashboard)
* Added nginx configuration validation as a step that runs on all branches.

### CODE REVIEW

**Review by kimlarocca — APPROVED** [review]
I'll leave this to Nico to review because he knows circleci much better than I do, but it looks good to me!

**Comment by allie-drake** [comment]
@ncastro-nypr Yeah that makes sense. I definitely could have at least squashed them, if not broken them up by function. Sorry for the sloppiness.

**Review by ncastro-nypr — CHANGES_REQUESTED** [review]
just the commit cleanup and it LGTM

**Review by ncastro-nypr — APPROVED** [review]
LGTM 👍

**Pull request merged**
